# Global chat
# Placeholders: %sender%, %message%
# WARNING: %sender% must come before %message%
chat: '&7%sender%&f: %message%'

# Private messaging
# Placeholders: %target%, %sender%, %message%
target: '&6From &7%sender%&f: %message%'
sender: '&6To &7%target%&f: %message%'

# Joining and leaving
# Placeholders: %player%
join: '%player% joined the game'
quit: '%player% left the game'

# Ignore command
# Placeholders: %target%
ignore: '&6Ignored %target%'
unignore: '&6Unignored %target%'
ignored-title: '&6Ignoring Players:'
entry: '&6%target%'
